const dashboardModules = [
  { path: '', name: 'dashboard.home', label: 'Dashboard', icon: 'DataBoard', roles: [], component: () => import('../views/Dashboard/DashboardHome.vue') },
  { path: 'admin/instituciones', name: 'dashboard.admin.instituciones', label: 'Instituciones', icon: 'OfficeBuilding', roles: ['Administrador'], component: () => import('../views/Admin/Instituciones.vue') },
  { path: 'admin/sedes', name: 'dashboard.admin.sedes', label: 'Sedes', icon: 'School', roles: ['Administrador'], component: () => import('../views/Admin/Sedes.vue') },
  { path: 'admin/usuarios', name: 'dashboard.admin.usuarios', label: 'Usuarios', icon: 'User', roles: ['Administrador'], component: () => import('../views/Admin/Usuarios.vue') },
  { path: 'admin/notificaciones', name: 'dashboard.admin.notificaciones', label: 'Notificaciones', icon: 'Notification', roles: ['Administrador'], component: () => import('../views/Admin/Notificaciones.vue') },
  { path: 'docente/cursos', name: 'dashboard.docente.cursos', label: 'Cursos', icon: 'Reading', roles: ['Docente'], component: () => import('../views/Docente/Cursos.vue') },
  { path: 'docente/calificaciones', name: 'dashboard.docente.calificaciones', label: 'Calificaciones', icon: 'Notebook', roles: ['Docente'], component: () => import('../views/Docente/Calificaciones.vue') },
  { path: 'docente/asistencia', name: 'dashboard.docente.asistencia', label: 'Asistencia', icon: 'Calendar', roles: ['Docente'], component: () => import('../views/Docente/Asistencia.vue') },
  { path: 'estudiante/mis-notas', name: 'dashboard.estudiante.notas', label: 'Mis Notas', icon: 'Notebook', roles: ['Estudiante'], component: () => import('../views/Estudiante/MisNotas.vue') },
  { path: 'estudiante/matriculas', name: 'dashboard.estudiante.matriculas', label: 'Matrículas', icon: 'Tickets', roles: ['Estudiante'], component: () => import('../views/Estudiante/Matriculas.vue') },
  { path: 'estudiante/horario', name: 'dashboard.estudiante.horario', label: 'Horario', icon: 'Calendar', roles: ['Estudiante'], component: () => import('../views/Estudiante/Horario.vue') },
  { path: 'tutor/tutorados', name: 'dashboard.tutor.tutorados', label: 'Tutorados', icon: 'User', roles: ['Tutor'], component: () => import('../views/Tutor/Tutorados.vue') },
  { path: 'tutor/seguimiento', name: 'dashboard.tutor.seguimiento', label: 'Seguimiento', icon: 'Document', roles: ['Tutor'], component: () => import('../views/Tutor/Seguimiento.vue') },
  { path: 'secretaria/actas', name: 'dashboard.secretaria.actas', label: 'Actas', icon: 'Document', roles: ['Secretaria Académica'], component: () => import('../views/Secretaria/Actas.vue') },
  { path: 'secretaria/certificados', name: 'dashboard.secretaria.certificados', label: 'Certificados', icon: 'Files', roles: ['Secretaria Académica'], component: () => import('../views/Secretaria/Certificados.vue') },
  { path: 'secretaria/titulaciones', name: 'dashboard.secretaria.titulaciones', label: 'Titulaciones', icon: 'Notebook', roles: ['Secretaria Académica'], component: () => import('../views/Secretaria/Titulaciones.vue') },
  { path: 'secretaria/admisiones', name: 'dashboard.secretaria.admisiones', label: 'Admisiones', icon: 'User', roles: ['Secretaria Académica'], component: () => import('../views/Secretaria/Admisiones.vue') },
  { path: 'finanzas/pagos', name: 'dashboard.finanzas.pagos', label: 'Pagos', icon: 'Money', roles: ['Tesorero'], component: () => import('../views/Finanzas/Pagos.vue') },
  { path: 'finanzas/becas', name: 'dashboard.finanzas.becas', label: 'Becas', icon: 'Tickets', roles: ['Tesorero'], component: () => import('../views/Finanzas/Becas.vue') },
  { path: 'finanzas/reportes', name: 'dashboard.finanzas.reportes', label: 'Reportes', icon: 'Document', roles: ['Tesorero'], component: () => import('../views/Finanzas/Reportes.vue') },
  { path: 'biblioteca/recursos', name: 'dashboard.biblioteca.recursos', label: 'Recursos', icon: 'Reading', roles: ['Bibliotecario'], component: () => import('../views/Biblioteca/Recursos.vue') },
  { path: 'biblioteca/prestamos', name: 'dashboard.biblioteca.prestamos', label: 'Préstamos', icon: 'Collection', roles: ['Bibliotecario'], component: () => import('../views/Biblioteca/Prestamos.vue') },
  { path: 'biblioteca/reservas', name: 'dashboard.biblioteca.reservas', label: 'Reservas', icon: 'Calendar', roles: ['Bibliotecario'], component: () => import('../views/Biblioteca/Reservas.vue') },
  { path: 'bienestar/psicologia', name: 'dashboard.bienestar.psicologia', label: 'Psicología', icon: 'User', roles: ['Tutor', 'Personal Administrativo'], component: () => import('../views/Bienestar/Psicologia.vue') },
  { path: 'bienestar/actividades', name: 'dashboard.bienestar.actividades', label: 'Actividades', icon: 'Bell', roles: ['Tutor', 'Personal Administrativo'], component: () => import('../views/Bienestar/Actividades.vue') },
  { path: 'bienestar/servicios', name: 'dashboard.bienestar.servicios', label: 'Servicios', icon: 'Files', roles: ['Tutor', 'Personal Administrativo'], component: () => import('../views/Bienestar/Servicios.vue') },
  { path: 'practicas/empresas', name: 'dashboard.practicas.empresas', label: 'Empresas', icon: 'OfficeBuilding', roles: ['Coordinador', 'Jefe de Carrera'], component: () => import('../views/Practicas/Empresas.vue') },
  { path: 'practicas/convenios', name: 'dashboard.practicas.convenios', label: 'Convenios', icon: 'Document', roles: ['Coordinador', 'Jefe de Carrera'], component: () => import('../views/Practicas/Convenios.vue') },
  { path: 'practicas/egresados', name: 'dashboard.practicas.egresados', label: 'Egresados', icon: 'User', roles: ['Coordinador', 'Jefe de Carrera'], component: () => import('../views/Practicas/Egresados.vue') },
  { path: 'practicas/bolsa-trabajo', name: 'dashboard.practicas.bolsa', label: 'Bolsa Trabajo', icon: 'Suitcase', roles: ['Coordinador', 'Jefe de Carrera'], component: () => import('../views/Practicas/BolsaTrabajo.vue') },
  { path: 'perfil', name: 'dashboard.perfil', label: 'Mi Perfil', icon: 'User', roles: [], component: () => import('../views/Perfil/MiPerfil.vue') },
]

export default dashboardModules
